apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-todo-java
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-java
  template:
    spec:
      containers:
        - image: quay.io/rh_rh/todo-java:latest
          name: bft-service
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 500m
              memory: 1.2Gi
            limits:
              cpu: 500m
              memory: 2.4Gi
