namespace: todo-java-dev
resources:
  - ../../../base/

patches:
  - path: deployment-todo-java.yaml
  - path: route-todo-java.yaml

configMapGenerator:
  - name: cm-todo-java
    literals:
      - java-tool-options="-server -Xms4096m -Xmx4096m"
      - spring-profiles-active="prod"
      - theme="green-theme"